import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { User } from 'firebase/auth';
import { api } from '../lib/api';
import { saveEntry } from '../lib/entrySave';
import { entrySaveCopy, onboardCopy } from '../lib/copy';
import { DEFAULT_REFLECTION_PREFERENCES } from '../../shared/schemas';
import ReflectionControls from '../components/ReflectionControls';

export default function Onboarding({ user, onDone }: { user: User; onDone: () => void }) {
  const [step, setStep] = useState<0 | 1>(0);
  const [entry, setEntry] = useState('');
  const [preferences, setPreferences] = useState(DEFAULT_REFLECTION_PREFERENCES);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [note, setNote] = useState('');
  const [savedBody, setSavedBody] = useState<string | null>(null);
  const navigate = useNavigate();

  async function finish() {
    if (!entry.trim() || busy) return;
    setBusy(true); setError(null); setNote('');
    const body = entry.trim();
    if (savedBody !== body) {
      const { outcome, final } = saveEntry(user, body);
      try {
        const result = await outcome;
        if (result === 'queued') setNote('Your entry is still syncing. Keep this page open until it is saved.');
        await final;
        setSavedBody(body);
      } catch (e) {
        setBusy(false); setNote(''); setError(entrySaveCopy(e)); return;
      }
    }
    try {
      await api.post('/api/profile/onboard', {
        tz: Intl.DateTimeFormat().resolvedOptions().timeZone,
        onboarded: true, reflectionPreferences: preferences, weeklyLetters: false, welcomeLetters: false,
      });
      onDone(); navigate('/');
    } catch (e) { setError(onboardCopy(e)); setBusy(false); }
  }

  return <div className="onboard">
    {step === 0 ? <>
      <p className="onboard-step">Step 1 of 2 · The practice and your depth</p>
      <h2>The practice</h2>
      <p>A journal for understanding yourself in a changing world. Write about what is on your mind, then invite an AI reflection when you want one.</p>
      <p>A small observation can be enough. You can also explore values, assumptions, or deeper questions about how to live.</p>
      <ReflectionControls value={preferences} onChange={setPreferences} />
      <details className="journal-preferences">
        <summary>Why Lucilio?</summary>
        <p>Lucilio takes inspiration from Seneca’s philosophical letters to Lucilius: explorations of friendship, uncertainty, ambition, and how to live. Here, your own experiences begin the inquiry. You do not need to know philosophy to begin.</p>
        <a href="https://iep.utm.edu/seneca/" target="_blank" rel="noopener noreferrer">Read about Seneca and the letters</a>
      </details>
      <p className="composer-hint">Reflections are generated by AI, not a person. Your writing is stored in your account; an entry you choose to reflect on is sent through our server to Gemini. AI interpretations can be wrong.</p>
      <button className="btn-primary" onClick={() => setStep(1)}>Begin — write a first entry</button>
    </> : <>
      <p className="onboard-step">Step 2 of 2 · Your first entry</p>
      <h2>Write a first entry</h2>
      <p>A moment from today, something you are carrying, or a question you have not resolved. One sentence is enough.</p>
      <div className="composer">
        <textarea autoFocus aria-label="Your first entry" value={entry} disabled={busy}
          onChange={(e) => setEntry(e.target.value)} placeholder="Today I have been thinking about…" />
        <div className="composer-bar">
          <span className="composer-hint">Saving does not request an AI response. You can reflect afterward.</span>
          <button className="btn-primary" onClick={finish} disabled={busy || !entry.trim() || new TextEncoder().encode(entry).length > 10 * 1024}>
            {busy ? 'Saving…' : 'Save entry and open my journal'}
          </button>
        </div>
      </div>
      <p className="composer-hint">
        What happens next: your journal opens with this entry saved. Nothing is sent to the AI until
        you invite a reflection, and correspondents will not write unless you ask them.
      </p>
      <button className="btn-quiet" disabled={busy} onClick={() => setStep(0)}>Back to reflection depth</button>
      {new TextEncoder().encode(entry).length > 10 * 1024 && <p role="alert">Please shorten your entry to 10 KB or less.</p>}
      {note && <p role="status">{note}</p>}
      {error && <div className="save-error" role="alert">{error}</div>}
    </>}
  </div>;
}
